services:
  postgres:
    image: postgres:16
    container_name: pantry_db 
    environment:
      POSTGRES_USER: pantry
      POSTGRES_PASSWORD: pantry123
      POSTGRES_DB: pantry_frankenstein
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pantry_pdadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pantry.com 
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  pgdata: # Will automatically pick up from the volumes part in postgres