"""rename standard to standard_unit

Revision ID: 9dda6b2f8e2d
Revises: 11b8418d06b8
Create Date: 2026-08-16 15:26:27.340078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dda6b2f8e2d'
down_revision: Union[str, Sequence[str], None] = '11b8418d06b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('standard_unit', sa.String(length=255), nullable=False))
    op.drop_column('ingredients', 'standard')
    op.drop_index(op.f('ix_pantry_expiration_date'), table_name='pantry')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_pantry_expiration_date'), 'pantry', ['expiration_date'], unique=False)
    op.add_column('ingredients', sa.Column('standard', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('ingredients', 'standard_unit')
    # ### end Alembic commands ###
